spring.application.name=Internal Issue Tracker
spring.config.import=optional:file:.env[.properties]

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.mvc.problemdetails.enabled=false
spring.web.error.include-message=never
spring.web.error.include-binding-errors=never
spring.web.error.include-stacktrace=never
spring.web.error.include-exception=false

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}