-- ============================================================
-- V1__init_schema.sql
-- Internal Issue Tracker - Initial Schema
-- ============================================================

-- ============================================================
-- TABLES
-- ============================================================

CREATE TABLE "users" (
                         "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "name" varchar(255) NOT NULL,
                         "surname" varchar(255) NOT NULL,
                         "email" varchar(255) UNIQUE NOT NULL,
                         "role" varchar(20) NOT NULL DEFAULT 'USER'
                             CHECK ("role" IN ('USER','DEVELOPER','EDITOR','ADMIN')),
                         "password_hashed" varchar(255) NOT NULL,
                         "is_active" boolean NOT NULL DEFAULT true,
                         "created_at" timestamptz DEFAULT (now()),
                         "updated_at" timestamptz
);

CREATE TABLE "teams" (
                         "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "name" varchar(255) UNIQUE NOT NULL,
                         "field" varchar(30)
                             CHECK ("field" IN ('BACKEND','FRONTEND','ANDROID','IOS','DESIGN','DATA')),
                         "leader_id" int NOT NULL,
                         "is_active" boolean DEFAULT true,
                         "created_at" timestamptz DEFAULT (now()),
                         "updated_at" timestamptz
);

CREATE TABLE "team_users" (
                              "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "team_id" int NOT NULL,
                              "user_id" int NOT NULL,
                              "is_active" boolean DEFAULT true,
                              "created_at" timestamptz DEFAULT (now()),
                              "updated_at" timestamptz
);

CREATE TABLE "projects" (
                            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "name" varchar(255) UNIQUE NOT NULL,
                            "description" text,
                            "start_date" date NOT NULL,
                            "end_date" date,
                            -- Nullable: a project can be opened before anyone is put in charge of
                            -- it, and a leader is named later. Teams are not like this.
                            "leader_id" int,
                            -- Where a live project stands, independent of "is_active", which only
                            -- records whether the row has been soft-deleted. A CANCELLED project
                            -- is still a visible row; a soft-deleted one is not.
                            "status" varchar(20) NOT NULL DEFAULT 'PLANNING'
                                CHECK ("status" IN ('PLANNING','ACTIVE','ON_HOLD','COMPLETED','CANCELLED')),
                            "is_active" boolean DEFAULT true,
                            "created_at" timestamptz DEFAULT (now()),
                            "updated_at" timestamptz
);

CREATE TABLE "project_teams" (
                                 "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 "team_id" int NOT NULL,
                                 "project_id" int NOT NULL,
                                 "is_active" boolean DEFAULT true,
                                 "created_at" timestamptz DEFAULT (now()),
                                 "updated_at" timestamptz
);

CREATE TABLE "project_users" (
                                 "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 "user_id" int NOT NULL,
                                 "project_id" int NOT NULL,
                                 "is_active" boolean DEFAULT true,
                                 "created_at" timestamptz DEFAULT (now()),
                                 "updated_at" timestamptz
);

CREATE TABLE "sprints" (
                           "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "project_id" int NOT NULL,
                           "name" varchar(255) NOT NULL,
                           "description" text,
                           "start_date" date NOT NULL,
                           "end_date" date,
                           "status" varchar(20) NOT NULL DEFAULT 'TODO'
                               CHECK ("status" IN ('TODO','IN_PROGRESS','TESTING','COMPLETED')),
                           "deleted_at" timestamptz,
                           "created_at" timestamptz DEFAULT (now()),
                           "updated_at" timestamptz
);

CREATE TABLE "epics" (
                         "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "project_id" int NOT NULL,
                         "name" varchar(255) NOT NULL,
                         "description" text,
                         "status" varchar(20) NOT NULL DEFAULT 'TODO'
                             CHECK ("status" IN ('TODO','IN_PROGRESS','ON_HOLD','COMPLETED','CANCELLED')),
                         "reporter_id" int NOT NULL,
                         "deleted_at" timestamptz,
                         "created_at" timestamptz DEFAULT (now()),
                         "updated_at" timestamptz
);

CREATE TABLE "issues" (
                          "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "project_id" int NOT NULL,
                          "sprint_id" int,
                          "epic_id" int,
                          "type" varchar(20)
                              CHECK ("type" IN ('BUG','FEATURE','STORY','TASK','ENHANCEMENT','REFACTOR')),
                          "name" varchar(255) NOT NULL,
                          "description" text,
                          "status" varchar(20) NOT NULL DEFAULT 'BACKLOG'
                              CHECK ("status" IN ('BACKLOG','TODO','IN_PROGRESS','IN_REVIEW','DONE','ON_HOLD','CANCELLED')),
                          "priority" varchar(20) NOT NULL DEFAULT 'MEDIUM'
                              CHECK ("priority" IN ('LOW','MEDIUM','HIGH','CRITICAL')),
                          "story_point" int,
                          "reporter_id" int NOT NULL,
                          "assignee_team_id" int,
                          "assignee_user_id" int,
                          "deleted_at" timestamptz,
                          "created_at" timestamptz DEFAULT (now()),
                          "updated_at" timestamptz
);

CREATE TABLE "comments" (
                            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "user_id" int NOT NULL,
                            "issue_id" int NOT NULL,
                            "content" text NOT NULL,
                            "deleted_at" timestamptz,
                            "created_at" timestamptz DEFAULT (now()),
                            "updated_at" timestamptz
);

CREATE TABLE "issue_activities" (
                                    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    "issue_id" int NOT NULL,
                                    "user_id" int NOT NULL,
                                    "action_type" varchar(30) NOT NULL
                                        CHECK ("action_type" IN ('CREATED','STATUS_UPDATED','PRIORITY_UPDATED','ASSIGNEE_USER_UPDATED',
                                                                 'ASSIGNEE_TEAM_UPDATED','SPRINT_UPDATED','STORY_POINT_UPDATED',
                                                                 'DETAILS_UPDATED','DELETED')),
                                    "old_value" varchar(255),
                                    "new_value" varchar(255),
                                    "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "sprint_activities" (
                                     "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "sprint_id" int NOT NULL,
                                     "user_id" int NOT NULL,
                                     "action_type" varchar(30) NOT NULL
                                         CHECK ("action_type" IN ('CREATED','STATUS_UPDATED','DATES_UPDATED','DETAILS_UPDATED','DELETED')),
                                     "old_value" varchar(255),
                                     "new_value" varchar(255),
                                     "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "project_activities" (
                                      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      "project_id" int NOT NULL,
                                      "user_id" int NOT NULL,
                                      "action_type" varchar(30) NOT NULL
                                          CHECK ("action_type" IN ('CREATED','LEADER_UPDATED','TEAM_ADDED','TEAM_REMOVED',
                                                                   'USER_ADDED','USER_REMOVED','DETAILS_UPDATED',
                                                                   'STATUS_UPDATED','DELETED')),
                                      "old_value" varchar(255),
                                      "new_value" varchar(255),
                                      "created_at" timestamptz DEFAULT (now())
);

-- ============================================================
-- FOREIGN KEYS
-- ============================================================

ALTER TABLE "teams" ADD FOREIGN KEY ("leader_id") REFERENCES "users" ("id");
ALTER TABLE "team_users" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("id");
ALTER TABLE "team_users" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "projects" ADD FOREIGN KEY ("leader_id") REFERENCES "users" ("id");
ALTER TABLE "project_teams" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("id");
ALTER TABLE "project_teams" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");
ALTER TABLE "project_users" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "project_users" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");
ALTER TABLE "sprints" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");
ALTER TABLE "epics" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");
ALTER TABLE "epics" ADD FOREIGN KEY ("reporter_id") REFERENCES "users" ("id");
ALTER TABLE "issues" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");
ALTER TABLE "issues" ADD FOREIGN KEY ("sprint_id") REFERENCES "sprints" ("id");
ALTER TABLE "issues" ADD FOREIGN KEY ("epic_id") REFERENCES "epics" ("id");
ALTER TABLE "issues" ADD FOREIGN KEY ("reporter_id") REFERENCES "users" ("id");
ALTER TABLE "issues" ADD FOREIGN KEY ("assignee_team_id") REFERENCES "teams" ("id");
ALTER TABLE "issues" ADD FOREIGN KEY ("assignee_user_id") REFERENCES "users" ("id");
ALTER TABLE "comments" ADD FOREIGN KEY ("issue_id") REFERENCES "issues" ("id");
ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "issue_activities" ADD FOREIGN KEY ("issue_id") REFERENCES "issues" ("id");
ALTER TABLE "issue_activities" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "sprint_activities" ADD FOREIGN KEY ("sprint_id") REFERENCES "sprints" ("id");
ALTER TABLE "sprint_activities" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "project_activities" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");
ALTER TABLE "project_activities" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

-- ============================================================
-- INDEXES (simple, non-conditional)
-- ============================================================

CREATE INDEX ON "users" ("is_active");

CREATE INDEX ON "teams" ("leader_id");
CREATE INDEX ON "teams" ("field");

CREATE INDEX ON "team_users" ("user_id");

CREATE INDEX ON "projects" ("leader_id");
CREATE INDEX ON "projects" ("is_active");
CREATE INDEX ON "projects" ("status");

CREATE INDEX ON "project_teams" ("project_id");

CREATE INDEX ON "project_users" ("project_id");

CREATE INDEX ON "sprints" ("project_id");
CREATE INDEX ON "sprints" ("status");
CREATE INDEX ON "sprints" ("project_id", "status");

CREATE INDEX ON "epics" ("project_id");
CREATE INDEX ON "epics" ("reporter_id");
CREATE INDEX ON "epics" ("status");

CREATE INDEX ON "issues" ("project_id");
CREATE INDEX ON "issues" ("sprint_id");
CREATE INDEX ON "issues" ("epic_id");
CREATE INDEX ON "issues" ("reporter_id");
CREATE INDEX ON "issues" ("assignee_user_id");
CREATE INDEX ON "issues" ("assignee_team_id");
CREATE INDEX ON "issues" ("status");
CREATE INDEX ON "issues" ("project_id", "status");
CREATE INDEX ON "issues" ("sprint_id", "status");
CREATE INDEX ON "issues" ("assignee_user_id", "status");

CREATE INDEX ON "comments" ("issue_id");
CREATE INDEX ON "comments" ("user_id");

CREATE INDEX ON "issue_activities" ("issue_id");
CREATE INDEX ON "issue_activities" ("user_id");

CREATE INDEX ON "sprint_activities" ("sprint_id");
CREATE INDEX ON "sprint_activities" ("user_id");

CREATE INDEX ON "project_activities" ("project_id");
CREATE INDEX ON "project_activities" ("user_id");

-- ============================================================
-- PARTIAL UNIQUE INDEXES (soft-delete'e duyarlı: join tablolarında
-- is_active=true iken, silinebilir domain entity'lerinde deleted_at IS NULL iken unique)
-- ============================================================

-- Bir kullanıcı aynı takıma birden fazla kez aktif olarak eklenemez
CREATE UNIQUE INDEX unique_active_team_membership
    ON "team_users" ("team_id", "user_id") WHERE "is_active" = true;

-- Bir takım aynı projeye birden fazla kez aktif olarak eklenemez
CREATE UNIQUE INDEX unique_active_project_team
    ON "project_teams" ("team_id", "project_id") WHERE "is_active" = true;

-- Bir kullanıcı aynı projeye birden fazla kez aktif olarak eklenemez
CREATE UNIQUE INDEX unique_active_project_user
    ON "project_users" ("user_id", "project_id") WHERE "is_active" = true;

-- Aynı projede aynı isimde iki silinmemiş sprint olamaz
CREATE UNIQUE INDEX unique_active_sprint_name_per_project
    ON "sprints" ("project_id", "name") WHERE "deleted_at" IS NULL;

-- Aynı projede aynı isimde iki silinmemiş epic olamaz
CREATE UNIQUE INDEX unique_active_epic_name_per_project
    ON "epics" ("project_id", "name") WHERE "deleted_at" IS NULL;

-- Bir projede aynı anda sadece bir sprint IN_PROGRESS olabilir
CREATE UNIQUE INDEX one_active_sprint_per_project
    ON "sprints" ("project_id") WHERE "status" = 'IN_PROGRESS';

-- ============================================================
-- SPRING MODULITH EVENT PUBLICATION REGISTRY
-- Verbatim from the reference documentation, not hand-written:
-- https://docs.spring.io/spring-modulith/reference/appendix.html#schemas.postgresql
-- ============================================================

CREATE TABLE IF NOT EXISTS event_publication
(
    id                     UUID NOT NULL,
    listener_id            TEXT NOT NULL,
    event_type             TEXT NOT NULL,
    serialized_event       TEXT NOT NULL,
    publication_date       TIMESTAMP WITH TIME ZONE NOT NULL,
    completion_date        TIMESTAMP WITH TIME ZONE,
    status                 TEXT,
    completion_attempts    INT,
    last_resubmission_date TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id)
    );
CREATE INDEX IF NOT EXISTS event_publication_serialized_event_hash_idx ON event_publication USING hash(serialized_event);
CREATE INDEX IF NOT EXISTS event_publication_by_completion_date_idx ON event_publication (completion_date);