-- ============================================================
-- V7__field_definitions.sql
-- Internal Issue Tracker - user-defined status/type/priority values
-- ============================================================
--
-- Replaces the CHECK-constrained enum vocabularies with rows a project can
-- add to, relabel and reorder. "kind" stays a fixed, small set of categories
-- (there are eight classification points in this app and that does not
-- change); it is the *values* under each kind that become data.
--
-- project_id NULL means: for PROJECT_STATUS and TEAM_FIELD, a real global
-- row (those two kinds are not project-scoped, see FieldKind#isGlobal);
-- for the other six kinds, the seed template V8 copies from into every
-- existing project, and that ProjectService#createProject copies from for
-- every project created from here on.

CREATE TABLE "field_definitions" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "kind" varchar(30) NOT NULL
        CHECK ("kind" IN ('PROJECT_STATUS','SPRINT_STATUS','EPIC_STATUS','ISSUE_STATUS',
                          'ISSUE_TYPE','ISSUE_PRIORITY','ISSUE_UNIT','TEAM_FIELD')),
    "project_id" int,
    "code" varchar(30) NOT NULL,
    "label" varchar(100) NOT NULL,
    "color" varchar(7),
    "sort_order" int NOT NULL DEFAULT 0,
    "is_active" boolean NOT NULL DEFAULT true,
    "is_default" boolean NOT NULL DEFAULT false,
    "is_done" boolean NOT NULL DEFAULT false,
    "is_cancelled" boolean NOT NULL DEFAULT false,
    "is_active_work" boolean NOT NULL DEFAULT false,
    "is_defect" boolean NOT NULL DEFAULT false,
    "created_at" timestamptz DEFAULT (now()),
    "updated_at" timestamptz
);

ALTER TABLE "field_definitions" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

-- A code is unique within its kind and project. COALESCE folds every global
-- row (project_id IS NULL) onto the same bucket per kind, since a plain
-- UNIQUE constraint treats NULLs as distinct and would let the same code be
-- inserted twice at the global scope.
CREATE UNIQUE INDEX unique_field_definition_code
    ON "field_definitions" ("kind", COALESCE("project_id", 0), "code");

-- At most one default per kind/project, and only among the rows still live.
CREATE UNIQUE INDEX unique_field_definition_default
    ON "field_definitions" ("kind", COALESCE("project_id", 0))
    WHERE "is_default" AND "is_active";

CREATE INDEX ON "field_definitions" ("kind", "project_id");

-- ============================================================
-- Global seed: PROJECT_STATUS and TEAM_FIELD rows (the two kinds that stay
-- global), plus the template rows V8 copies into every existing project and
-- FieldDefinitionProvisioning#seedDefaults copies into every project created
-- from now on. Flags mirror MetricStatus.ACTIVE / .COMPLETED and the BUG
-- special-case in IssueMetricsRepository, so today's metric numbers keep
-- meaning what they meant before this migration.
-- ============================================================

INSERT INTO "field_definitions"
    ("kind", "project_id", "code", "label", "sort_order", "is_default", "is_done", "is_cancelled", "is_active_work", "is_defect")
VALUES
    -- PROJECT_STATUS (global)
    ('PROJECT_STATUS', NULL, 'PLANNING',  'Planning',  0, true,  false, false, false, false),
    ('PROJECT_STATUS', NULL, 'ACTIVE',    'Active',    1, false, false, false, true,  false),
    ('PROJECT_STATUS', NULL, 'ON_HOLD',   'On Hold',   2, false, false, false, false, false),
    ('PROJECT_STATUS', NULL, 'COMPLETED', 'Completed', 3, false, true,  false, false, false),
    ('PROJECT_STATUS', NULL, 'CANCELLED', 'Cancelled', 4, false, false, true,  false, false),

    -- TEAM_FIELD (global, no lifecycle semantics)
    ('TEAM_FIELD', NULL, 'BACKEND',  'Backend',  0, false, false, false, false, false),
    ('TEAM_FIELD', NULL, 'FRONTEND', 'Frontend', 1, false, false, false, false, false),
    ('TEAM_FIELD', NULL, 'ANDROID',  'Android',  2, false, false, false, false, false),
    ('TEAM_FIELD', NULL, 'IOS',      'iOS',      3, false, false, false, false, false),
    ('TEAM_FIELD', NULL, 'DESIGN',  'Design',   4, false, false, false, false, false),
    ('TEAM_FIELD', NULL, 'DATA',    'Data',     5, false, false, false, false, false),

    -- SPRINT_STATUS (project-scoped template)
    ('SPRINT_STATUS', NULL, 'TODO',        'To Do',       0, true,  false, false, false, false),
    ('SPRINT_STATUS', NULL, 'IN_PROGRESS', 'In Progress', 1, false, false, false, true,  false),
    ('SPRINT_STATUS', NULL, 'TESTING',     'Testing',     2, false, false, false, false, false),
    ('SPRINT_STATUS', NULL, 'COMPLETED',   'Completed',   3, false, true,  false, false, false),

    -- EPIC_STATUS (project-scoped template)
    ('EPIC_STATUS', NULL, 'TODO',        'To Do',       0, true,  false, false, false, false),
    ('EPIC_STATUS', NULL, 'IN_PROGRESS', 'In Progress', 1, false, false, false, true,  false),
    ('EPIC_STATUS', NULL, 'ON_HOLD',     'On Hold',     2, false, false, false, false, false),
    ('EPIC_STATUS', NULL, 'COMPLETED',   'Completed',   3, false, true,  false, false, false),
    ('EPIC_STATUS', NULL, 'CANCELLED',   'Cancelled',   4, false, false, true,  false, false),

    -- ISSUE_STATUS (project-scoped template)
    ('ISSUE_STATUS', NULL, 'BACKLOG',     'Backlog',     0, true,  false, false, false, false),
    ('ISSUE_STATUS', NULL, 'TODO',        'To Do',       1, false, false, false, false, false),
    ('ISSUE_STATUS', NULL, 'IN_PROGRESS', 'In Progress', 2, false, false, false, true,  false),
    ('ISSUE_STATUS', NULL, 'IN_REVIEW',   'In Review',   3, false, false, false, true,  false),
    ('ISSUE_STATUS', NULL, 'DONE',        'Done',        4, false, true,  false, false, false),
    ('ISSUE_STATUS', NULL, 'ON_HOLD',     'On Hold',     5, false, false, false, false, false),
    ('ISSUE_STATUS', NULL, 'CANCELLED',   'Cancelled',   6, false, false, true,  false, false),

    -- ISSUE_TYPE (project-scoped template)
    ('ISSUE_TYPE', NULL, 'BUG',         'Bug',         0, false, false, false, false, true),
    ('ISSUE_TYPE', NULL, 'FEATURE',     'Feature',     1, false, false, false, false, false),
    ('ISSUE_TYPE', NULL, 'STORY',       'Story',       2, false, false, false, false, false),
    ('ISSUE_TYPE', NULL, 'TASK',        'Task',        3, true,  false, false, false, false),
    ('ISSUE_TYPE', NULL, 'ENHANCEMENT', 'Enhancement', 4, false, false, false, false, false),
    ('ISSUE_TYPE', NULL, 'REFACTOR',    'Refactor',    5, false, false, false, false, false),

    -- ISSUE_PRIORITY (project-scoped template)
    ('ISSUE_PRIORITY', NULL, 'LOW',      'Low',      0, false, false, false, false, false),
    ('ISSUE_PRIORITY', NULL, 'MEDIUM',   'Medium',   1, true,  false, false, false, false),
    ('ISSUE_PRIORITY', NULL, 'HIGH',     'High',     2, false, false, false, false, false),
    ('ISSUE_PRIORITY', NULL, 'CRITICAL', 'Critical', 3, false, false, false, false, false),

    -- ISSUE_UNIT (project-scoped template, no default - stays unset until triage)
    ('ISSUE_UNIT', NULL, 'BACKEND',  'Backend',  0, false, false, false, false, false),
    ('ISSUE_UNIT', NULL, 'FRONTEND', 'Frontend', 1, false, false, false, false, false),
    ('ISSUE_UNIT', NULL, 'IOS',      'iOS',      2, false, false, false, false, false),
    ('ISSUE_UNIT', NULL, 'ANDROID',  'Android',  3, false, false, false, false, false);
